POST http://localhost:3001/api/notes 
Content-type: application/json

{
    "content": "Cositas por aquí",
    "important": true,
    "userId": "6066078806a99b0a0805b091"
}

###

POST http://localhost:3001/api/notes 
Content-type: application/json

{
}