DELETE  http://localhost:3001/api/notes/606787a2a3ba6a2fc081b544
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFsZXhzbzQ3IiwiaWQiOiI2MDY3ODZjNWEzYmE2YTJmYzA4MWI1NDIiLCJpYXQiOjE2MTczOTc0NjIsImV4cCI6MTYxODAwMjI2Mn0.kPhr0pM_Ku-8KYvnLRsUdhT5_KmudnmPj9a399QoH50